# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachments',
            name='url_x480',
        ),
        migrations.RemoveField(
            model_name='postattachments',
            name='url_x600',
        ),
    ]
