# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='tags',
            field=models.CharField(default='', max_length=4096, verbose_name='tags in post'),
        ),
    ]
