# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachments',
            name='attach_type',
            field=models.TextField(blank=True, null=True, verbose_name='Attachments type'),
        ),
    ]
