# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Tag mentioned in post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runstat.GroupMember', verbose_name='group member')),
            ],
        ),
    ]
