# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0002_postattachments_attach_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachments',
            name='title',
        ),
    ]
