# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0002_auto_20160508_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runstat.PostPhoto', verbose_name='post photo'),
        ),
        migrations.AddField(
            model_name='postphoto',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='runstat.GroupPost', verbose_name='post'),
            preserve_default=False,
        ),
    ]
