# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0002_membertag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membertag',
            unique_together=set([('author', 'tag')]),
        ),
    ]
