# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0003_auto_20160519_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runstat.GroupMember', verbose_name='author object id'),
        ),
    ]
