# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0003_auto_20160510_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='created_time',
            field=models.DateTimeField(default=None, verbose_name='post created time'),
        ),
    ]
