# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0004_grouppost_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='created_time',
            field=models.DateTimeField(verbose_name='post created time'),
        ),
    ]
