# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0004_auto_20160520_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachments',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
