# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0005_auto_20160510_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='photo',
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='tags',
            field=models.CharField(default='', max_length=4096, null=True, verbose_name='tags in post'),
        ),
    ]
