# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runstat', '0009_auto_20160510_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='object_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='post object id'),
        ),
    ]
